# Introduction

## Workflow

<!-- 
Insert here RStudio, Atom, Jupyter, VSCode, ...

Speak about: the aim of this presentation, objectives, etc

- Present the problematics of the IDE hoice
- Remind about tastes
- Remond about the absence of the absolute choice
-->

https://insights.stackoverflow.com/survey/2019#technology-_-most-popular-development-environments - insert graph 

## Workflow types

- Text editor
- Notebooks
- IDE



# What is RStudio 

## An IDE that was built just for R

- Syntax highlighting, code completion, and smart indentation
- Execute R code directly from the source editor
- Quickly jump to function definitions

## Bring your workflow together

- Integrated R help and documentation
- Easily manage multiple working directories using projects
- Workspace browser and data viewer

## Powerful authoring & Debugging

- Interactive debugger to diagnose and fix errors quickly
- Extensive package development tools
- Authoring with Sweave and R Markdown

## And more

- Runs on most desktops or on a server and accessed over the web
- Integrates the tools you use with R into a single environment
- Includes powerful coding tools designed to enhance your productivity
- Enables rapid navigation to files and functions
- Make it easy to start new or find existing projects
- Has integrated support for Git and Subversion
- Supports authoring HTML, PDF, Word Documents, and slide shows
- Supports interactive graphics with Shiny and ggvis



# What RStudio is not ...

## Multi-language DE 

<!-- 
Add here some information about the alternative languages
-->



# What about others ?

# Jupyter

## Key advertising factors

<!--
The notebook extends the console-based approach to interactive computing in a qualitatively new direction, providing a web-based application suitable for capturing the whole computation process: developing, documenting, and executing code, as well as communicating the results. 
The Jupyter notebook combines two components:
-->

* A web application 

<!--
a browser-based tool for interactive authoring of documents which combine explanatory text, mathematics, computations and their rich media output.
-->

* Notebook documents

<!--
a representation of all content visible in the web application, including inputs and outputs of the computations, explanatory text, mathematics, images, and rich media representations of objects.
-->

## Features

- In-browser editing for code, with automatic syntax highlighting, indentation, and tab completion/introspection.
- The ability to execute code from the browser, with the results of computations attached to the code which generated them.
- Displaying the result of computation using rich media representations, such as HTML, LaTeX, PNG, SVG, etc. For example, publication-quality figures rendered by thematplotlib library, can be included inline.
- In-browser editing for rich text using the Markdown markup language, which can provide commentary for the code, is not limited to plain text.
- The ability to easily include mathematical notation within markdown cells using LaTeX, and rendered natively by MathJax.

<!-- Add here some screenshots / pics for clarity -->

## Drawbacks 

## Version control

<!--
Aff screenshot

Version control of files with tools such as git is important as it both maintains an explorable database of changes to the code files and also improves collaboration by using a centralized server (e.g. GitHub) where anyone with access to the repository can pull and push changes to the code. In the data science world, large startups such as Stripe and Airbnb have seen a lot of success with this approach.

RStudio incidentally has a native git client for tracking and committing changes to a .Rmd file, which is easy since .Rmd files are effectively plain text files where you can see differences between versions at a per-line level. (You may not want to store the changes to the generated .nb.html Notebook since they will be large and redundant to the changes made in the corresponding .Rmd; I recommend adding a *.nb.html rule to a .gitignore file during analysis).

The .ipynb Jupyter Notebook files are blobs of JSON that also store cell output, which will result in large diffs if you keep them in version control and make any changes which result in different output. This can cause the git database to balloon and makes reading per-line diffs hard if not impossible.

On Hacker News, the version control issues in Jupyter are a common complaint, however a Jupyter developer noted of a possibility of working with RStudio on solving this issue.
-->

## Inline Code Rendering

<!--
Add image

A common practice in Jupyter Notebooks is to print common values as a part of a write-up or testing statistical code. 
In Jupyter Notebooks, if you want to verify the number of rows in a dataset for exploratory data analysis, you have to add an appropriate print statement to the cell to get the number n rows, and then add a Markdown cell to redundantly describe what you just print in the output.

In R Notebooks, you can skip a step by calling such print statements in-line in the Markdown text, which will then be rendered with the Notebook. This also avoids hard-coding such numbers in
-->



# VS Code 

# VS Code features

From: https://code.visualstudio.com/docs/editor/whyvscode

Visual Studio Code combines the simplicity of a source code editor with powerful developer tooling, like IntelliSense code completion and debugging.

First and foremost, it is an editor that gets out of your way. The delightfully frictionless edit-build-debug cycle means less time fiddling with your environment, and more time executing on your ideas.

## Available for macOS, Linux, and Windows

Visual Studio Code supports macOS, Linux, and Windows - so you can hit the ground running, no matter the platform.

## Edit, build, and debug with ease

At its heart, Visual Studio Code features a lightning fast source code editor, perfect for day-to-day use. With support for hundreds of languages, VS Code helps you be instantly productive with syntax highlighting, bracket-matching, auto-indentation, box-selection, snippets, and more. Intuitive keyboard shortcuts, easy customization and community-contributed keyboard shortcut mappings let you navigate your code with ease.

For serious coding, you'll often benefit from tools with more code understanding than just blocks of text. Visual Studio Code includes built-in support for IntelliSense code completion, rich semantic code understanding and navigation, and code refactoring.

And when the coding gets tough, the tough get debugging. Debugging is often the one feature that developers miss most in a leaner coding experience, so we made it happen. Visual Studio Code includes an interactive debugger, so you can step through source code, inspect variables, view call stacks, and execute commands in the console.

VS Code also integrates with build and scripting tools to perform common tasks making everyday workflows faster. VS Code has support for Git so you can work with source control without leaving the editor including viewing pending changes diffs.

## Make it your own

Customize every feature to your liking and install any number of third-party extensions. While most scenarios work "out of the box" with no configuration, VS Code also grows with you, and we encourage you to optimize your experience to suit your unique needs. VS Code is an open-source project so you can also contribute to the growing and vibrant community on GitHub.

## Built with love for the Web

VS Code includes enriched built-in support for Node.js development with JavaScript and TypeScript, powered by the same underlying technologies that drive Visual Studio. VS Code also includes great tooling for web technologies such as JSX/React, HTML, CSS, SCSS, Less, and JSON.

## Robust and extensible architecture

Architecturally, Visual Studio Code combines the best of web, native, and language-specific technologies. Using Electron, VS Code combines web technologies such as JavaScript and Node.js with the speed and flexibility of native apps. VS Code uses a newer, faster version of the same industrial-strength HTML-based editor that has powered the “Monaco” cloud editor, Internet Explorer's F12 Tools, and other projects. Additionally, VS Code uses a tools service architecture that enables it to integrate with many of the same technologies that power Visual Studio, including Roslyn for .NET, TypeScript, the Visual Studio debugging engine, and more.

Visual Studio Code includes a public extensibility model that lets developers build and use extensions, and richly customize their edit-build-debug experience.

## Ready, set, code!

If you prefer a code editor-centric development tool or are building cross-platform web and cloud applications, we invite you to try out Visual Studio Code and let us know what you think!